name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build installer (NSIS)
        run: npm run make

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: password-vault-installer
          path: dist/**/*.exe
