name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches: [ main ]

# <<— Hacemos que todos los "run" se ejecuten dentro de la carpeta del proyecto
defaults:
  run:
    working-directory: password-vault-electron-ci

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Usa "npm install" si no tienes package-lock.json
      - name: Install dependencies
        run: npm install

      - name: Build UI
        run: npm run build:ui

      - name: Build installer (NSIS) con electron-builder
        run: npx electron-builder --win --x64 --publish=never

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: password-vault-installer
          path: dist/**/*.exe
